name: Build Repo

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y dpkg-dev

    - name: Generate Packages
      run: |
        dpkg-scanpackages debs /dev/null > Packages
        gzip -kf Packages

    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        git add Packages Packages.gz

        git diff --cached --quiet || \
        git commit -m "update repo"

        git push
